### ISSUE TITLE
Arduino UNO (SMD) - D4 as Output and OSC is not working?

### ISSUE THREAD

**Issue by joschy3D** [thomasfredericks/MicroOsc#11]
Hello,
don't know if this belongs to the OSC library, but I found some strange behavior.
Setup is an Arduino UNO with an Ethernet shield Rev. 2.
When I use the D4 Pin for digital output, nothing works.

int addressPins[] = {2, 3, 5, 6};  -> works

int addressPins[] = {2, 3, 4, 5};  -> don't work

  for (int j = 0; j <= 3; j++) {
    pinMode(addressPins[j], OUTPUT);
  }

cheers

**Comment by thomasfredericks** [comment]
`MicroOsc `does not configure any pins or any Ethernet devices. You should ask your questions to the developers of the hardware in question. 

Closing this issue.
